AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'CloudFormation Template for creating a S3 bucket to host a static website.
  Also creates a Route 53 DNS record for the URL of the website, and an IAM user to
  be used for uploading content to the bucket via wp2static plugin.'
Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  SubdomainName:
    Type: String
    Description: The subdomain name of the website. (E.g, "www")
    AllowedPattern: (?!-)[a-zA-Z0-9-]{1,63}(?<!-)
    ConstraintDescription: must be a valid subdomain name
Mappings:
  Region2S3Info:
    us-east-2:
      HostedZoneID: Z2O1EMRO9K5GLX 
      Suffix: s3-website.us-east-2.amazonaws.com
    us-east-1:
      HostedZoneID: Z3AQBSTGFYJSTF
      Suffix: s3-website-us-east-1.amazonaws.com
    us-west-1:
      HostedZoneID: Z2F56UZL2M1ACD
      Suffix: s3-website-us-west-1.amazonaws.com
    us-west-2:
      HostedZoneID: Z3BJ6K6RIION7M
      Suffix: s3-website-us-west-2.amazonaws.com
    ap-east-1:
      HostedZoneID: ZNB98KWMFR0R6
      Suffix: s3-website.ap-east-1.amazonaws.com
    ap-south-1:
      HostedZoneID: Z11RGJOFQNVJUP
      Suffix: s3-website.ap-south-1.amazonaws.com
    ap-northeast-3:
      HostedZoneID: Z2YQB5RD63NC85
      Suffix: s3-website.ap-northeast-3.amazonaws.com
    ap-northeast-2:
      HostedZoneID: Z3W03O7B5YMIYP
      Suffix: s3-website.ap-northeast-2.amazonaws.com
    ap-southeast-1:
      HostedZoneID: Z3O0J2DXBE1FTB
      Suffix: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      HostedZoneID: Z1WCIGYICN2BYD
      Suffix: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      HostedZoneID: Z2M4EHUR26P7ZW
      Suffix: s3-website-ap-northeast-1.amazonaws.com
    ca-central-1:
      HostedZoneID: Z1QDHH18159H29
      Suffix: s3-website-ca-central-1.amazonaws.com
    eu-central-1:
      HostedZoneID: Z21DNDUVLTQW6Q
      Suffix: s3-website.eu-central-1.amazonaws.com
    eu-west-1:
      HostedZoneID: Z1BKCTXD74EZPE
      Suffix: s3-website-eu-west-1.amazonaws.com
    eu-west-2:
      HostedZoneID: Z3GKZC51ZF0DB4
      Suffix: s3-website.eu-west-2.amazonaws.com
    eu-west-3:
      HostedZoneID: Z3R1K369G5AVDG
      Suffix: s3-website.eu-west-3.amazonaws.com
    eu-north-1:
      HostedZoneID: Z3BAZG2TWCNX0D
      Suffix: s3-website.eu-north-1.amazonaws.com
    sa-east-1:
      HostedZoneID: Z7KQH4QJS55SO
      Suffix: s3-website-sa-east-1.amazonaws.com
    me-south-1:
      HostedZoneID: Z1MPMWCPA7YB62
      Suffix: s3-website.me-south-1.amazonaws.com
Conditions:
  NoSubdomain: !Equals [ !Ref SubdomainName, '' ]
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [ NoSubdomain, !Ref 'HostedZone',
        !Join ['', [!Ref 'SubdomainName', ., !Ref 'HostedZone']] ]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !If [ NoSubdomain, !Ref 'HostedZone',
        !Join ['', [!Ref 'SubdomainName', ., !Ref 'HostedZone']] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !GetAtt S3BucketUser.Arn
          Action:
          - 's3:ListBucket'
          - 's3:PutObject*'
          - 's3:GetObject'
          - 's3:DeleteObject'
          - 's3:PutBucket*'
          Resource:
          - !Join ['', 
              [ 'arn:aws:s3:::', 
                !If [ NoSubdomain, !Ref 'HostedZone',
                  !Join ['', [!Ref 'SubdomainName', ., !Ref 'HostedZone']] ]
              ]
            ]
          - !Join ['', 
              [ 'arn:aws:s3:::', 
                !If [ NoSubdomain, !Ref 'HostedZone',
                  !Join ['', [!Ref 'SubdomainName', ., !Ref 'HostedZone']] ],
                '/*'
              ]
            ]
  S3BucketUser:
    Type: AWS::IAM::User
  S3BucketUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref S3BucketUser
  WebsiteDNSName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      Comment: CNAME redirect custom name to CloudFront distribution
      Name: !If [ NoSubdomain, !Ref 'HostedZone',
        !Join ['', [!Ref 'SubdomainName', ., !Ref 'HostedZone']] ]
      Type: A
      AliasTarget:
        HostedZoneId: !FindInMap [Region2S3Info, !Ref 'AWS::Region', HostedZoneID]
        DNSName: !FindInMap [Region2S3Info, !Ref 'AWS::Region', Suffix]
Outputs:
  WebsiteURL:
    Value: !If [ NoSubdomain, !Ref 'HostedZone',
        !Join ['', [!Ref 'SubdomainName', ., !Ref 'HostedZone']] ]
    Description: The URL of the website
  BucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket for the website
  S3UserName:
    Value: !Ref 'S3BucketUser'
    Description: IAM User for pushing data to the S3 bucket
  S3UserAccessKeyID:
    Value: !Ref 'S3BucketUserAccessKey'
    Description: Access Key ID for the IAM User
  S3UserSecretAccessKey:
    Value: !GetAtt 'S3BucketUserAccessKey.SecretAccessKey'
    Description: Secret Access Key for the IAM User
